# M: 프로퍼티 파일을 이용한 환경 설정 주입하기 - yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password:
  application:
    name: spring-basics
  aop:
    proxy-target-class: true
