import type { Metadata } from "next";
import { Provider } from '@/components/ui/provider'
import Layout from '@/components/Layout'
import React, { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <Layout>
      {children}
    </Layout>
  )
}

export default RootLayout