spring:
  application:
    name: database-orm
  config:
    import: optional:file:dev.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    show-sql: true

  sql:
    init:
      mode: always

  jwt:
    secret: 405fcfca6a5856531ed90fce769cf4a3b1027c757b2d7eeb352521115b7ce707

mybatis:
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true