spring:
  application:
    name: spring-advanced
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2-console